version: '3'
services:
  db:
    container_name: db
    image: registry.redhat.io/rhel8/postgresql-13
    environment:
      - POSTGRESQL_USER=postgresUser
      - POSTGRESQL_PASSWORD=postgresPW
      - POSTGRESQL_DATABASE=naloga
    networks: 
      - db
    volumes:
      - db:/var/lib/pgsql/data
    ports:
      - "5432:5432"


  backend:
    container_name: app-ba
    image: quay.ts.telekom.si/learning/jrejec/app-ba:1.0.0
    networks:
      - fe
      - db
    depends_on: db
    ports: 
      - "3001:3001"

  frontend:
    container_name: app-fe
    image: quay.ts.telekom.si/learning/jrejec/app-fe:1.0.0
    networks: 
      - fe
    ports:
      - "3000:3000"

networks:
  fe:
  db:

volumes: 
  db:
    driver: local


    



